wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.3
    cli_version: 0.15.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697129278.193713
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.3
      5: 0.15.11
      8:
      - 1
      - 5
      13: linux-x86_64
