wandb_version: 1

activation:
  desc: null
  value: tanh
epochs:
  desc: null
  value: 50
hiddenlayersize:
  desc: null
  value:
  - 14
learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Batch
_wandb:
  desc: null
  value:
    python_version: 3.10.3
    cli_version: 0.15.11
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697171087.562891
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.3
      5: 0.15.11
      8:
      - 1
      - 5
      13: linux-x86_64
