wandb_version: 1

dropout_rate:
  desc: null
  value: 0.5
kernel_size:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697968791.576947
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.12
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
